### ISSUE TITLE
Trying to run the example, no points are displayed on the map.

### ISSUE THREAD

**Issue by rvlander** [mapbox/mapboxgl-jupyter#10]
**Configuration:**
* Python: 3.6.2
* Chrome: Version 61.0.3163.100

The maps is displayed, is correctly centered and zoomed, but no points are displayed.

**Comment by ryanbaumann** [comment]
@rvlander thanks for the bug report!  Were you able to successfully load the local file into a dataframe in the prior cells in the example notebook?

**Comment by rvlander** [comment]
@ryanbaumann, yes, I just had to generate color breaks manually since `jenks` seems broken.

I also tried with my data (before trying your example), and nothing was showing up too.

**Comment by rvlander** [comment]
Just tested with Firefox, the problem remains.

**Comment by ryanbaumann** [comment]
Interesting @rvlander.  

Can you share a screenshot or attach the HTML? 

What is the output of the viz.create_html() command if you run it in cell 11?

![](https://cl.ly/3A2o1I1D1U2e/download/Image%202017-09-28%20at%2012.45.36%20PM.png)

**Comment by rvlander** [comment]
There are no errors displayed in the javascript console.
Here is a part the generated html:
![mapbox_glhtml](https://user-images.githubusercontent.com/5236428/31004701-c44a4870-a4f5-11e7-88be-f3d7d800dcf6.png)

**Comment by ryanbaumann** [comment]
@rvlander interesting.  I was able to re-create on a fresh machine that couldn't install the C-binding version of jenks.

I updated the example in the master branch to use a `slow` but python-only version of jenks.  Let me know if that works on the current master branch!

**Comment by ryanbaumann** [comment]
@rvlander 

* What values did you use for your color stops when you were unable to see the points plotted on the map?  

* Can you open up a new ticket to track the issue below:

> What if I want to display plots with the same colour (using no property)?

**Comment by ryanbaumann** [comment]
The latest `examples` notebook now uses the PySAL library to calculate data domain breaks.  Check out the example in the latest master branch and [here](www.mapbox.com/labs/jupyter)

**Comment by dljthomas1** [comment]
Hi folks - I seem to be having a variant of the issue above. I am trying to run the example from [here](https://github.com/mapbox/mapboxgl-jupyter). The map is displaying fine. However, the points/data are missing.

![Screenshot 2019-04-17 at 11 18 13](https://user-images.githubusercontent.com/48061064/56280643-87578700-6102-11e9-967c-3f600ad50001.png)

Some points worth mentioning:

- I've ran this in Google Colab and on my own Jupyter machine to make sure its not an issue with the environment. I've also ran in Python 2 and 3.

- There is a javascript error in the console whenever I run the code. See below. 

![Screenshot 2019-04-17 at 11 21 59](https://user-images.githubusercontent.com/48061064/56280872-0f3d9100-6103-11e9-9b28-c4880742a8e3.png)

Thanks in advance for your help!

Also see my code below:

```
import os

import pandas as pd

from mapboxgl.utils import create_color_stops, df_to_geojson
from mapboxgl.viz import CircleViz


# Load data from sample csv
data_url = 'https://raw.githubusercontent.com/mapbox/mapboxgl-jupyter/master/examples/data/points.csv'
df = pd.read_csv(data_url)

# Must be a public token, starting with `pk`
token = 'pk.eyJ1IjoiYnVzaW5lc3NvZmNpdGllcyIsImEiOiJjanVqdHF0NHQxazczNGFxamZydmQ2NmRzIn0.oZStPDr7CsZIFTemgdr-cw'


# Create a geojson file export from a Pandas dataframe
df_to_geojson(df, filename='points.geojson',
              properties=['Avg Medicare Payments', 'Avg Covered Charges', 'date'],
              lat='lat', lon='lon', precision=3)

# Generate data breaks and color stops from colorBrewer
color_breaks = [0,10,100,1000,10000]
color_stops = create_color_stops(color_breaks, colors='YlGnBu')

# Create the viz from the dataframe
viz = CircleViz('points.geojson',
                access_token=token,
                height='400px',
                color_property = "Avg Medicare Payments",
                color_stops = color_stops,
                center = (-95, 40),
                zoom = 1,
                below_layer = 'waterway-label'
              )
viz.show()
```
