### ISSUE TITLE
Example Documentation Loads Map but no Points

### ISSUE THREAD

**Issue by hunterowens** [mapbox/mapboxgl-jupyter#102]
Hi! 

I'm trying to make the example plots render, spefically, the CADC Points example. However, I get the followed `evented` error in chrome and the plot only renders a map/legend, no points. 
<img width="1440" alt="screen shot 2018-06-10 at 15 13 20" src="https://user-images.githubusercontent.com/1735650/41206914-fbec1720-6cc0-11e8-8418-9e84ae47fc19.png">

**Comment by hunterowens** [comment]
Using chrome, python3, mac os x.

**Comment by hunterowens** [comment]
Hi @ryanbaumann. I have run the examples in the example directory from master on the `point-viz-categorical` notebook. See screenshot of error. 

<img width="1436" alt="screen shot 2018-06-11 at 10 44 26" src="https://user-images.githubusercontent.com/1735650/41248042-96f2bb5e-6d64-11e8-8ceb-3c5dcc120b7f.png">

**Comment by ryanbaumann** [comment]
Great, thanks for the screenshot.  Looks like you're using Jupyter Lab - Jupyter Lab does not support the same method for loading local resources (a local geojson file).  Can you try the examples using `juypter notebook`?  

Jupyter lab is supported using in-line geojson sources.  Details here - https://github.com/mapbox/mapboxgl-jupyter/issues/50

**Comment by hunterowens** [comment]
Works, thanks @ryanbaumann. 

I'm going to close this issue, but I think it would be helpful to have some sort of warning message for MapboxGL in the lab environment. How much of a lift would a PR be on that?

**Comment by ryanbaumann** [comment]
Thanks @hunterowens.  The ideal PR would be to figure out what the URL prefix should be in Jupyter Lab to access local resources https://github.com/mapbox/mapboxgl-jupyter/issues/50#issuecomment-385781213, or to just use a local geojson format object instead of loading the geojson via an HTTP get request for the examples.
