### ISSUE TITLE
Default width in LineString Vis is coerced to a sting

### ISSUE THREAD

**Issue by jamiecook** [mapbox/mapboxgl-jupyter#108]
I believe that this line in the linestring vis has the same problem as reported in #72 

https://github.com/mapbox/mapboxgl-jupyter/blob/master/mapboxgl/templates/linestring.html#L61

specifically ![image](https://user-images.githubusercontent.com/151124/41384726-d02831b2-6fba-11e8-94ff-86010ab5e5e3.png)

**Comment by ryanbaumann** [comment]
Thanks for the bug!  Yes, this is the same bug.  Fix is to remove the double quotes in the linestring template around `{{defaultWidth }}`.

**Comment by jamiecook** [comment]
Thanks @ryanbaumann ... i wasn't sure if there were other aspects of #74 that were also applicable otherwise I would have just raised a PR... I'll do that now
