### ISSUE TITLE
Package Jenks with `mapboxgl` library

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-jupyter#11]
Users have reported issues installing the `jenks` package via 
* pip install -e "git+https://github.com/perrygeo/jenks.git#egg=jenks"

We should bundle up `jenks` with the `mapboxgl` library, as it will be one of the most common breaks classifiers to use on a domain of values.

 cc @perrygeo

**Comment by perrygeo** [comment]
What specific problems are users having installing jenks? I'd anticipate two main issues:

1. they don't have `git` installed
2. they don't have a compiler toolchain to build C extension modules

Publishing an official release of the `jenks` module to pypi will solve (1) - Just `pip install jenks`. Honestly something I should do anyways. I'd much prefer to do this than fork the code and bundle it with an unrelated repo.

But (2) will still be an issue - the jenks module is implemented in Cython for speed reasons and needs a C compiler to work. This will typically affect Windows users more severly as the compiler toolchain is very easy to install on OSX and Linux. A few options to solve this 

* Build binary wheels for every target platform and python version
* Rewrite the module setup to fall back onto a (slow but working) pure python implementation in the absence of a compiler.
* Rely on another third party classification library that has these issues solved:
    - PySAL has a very robust module for handling classification with Jenks and other methods: https://pysal.readthedocs.io/en/latest/library/esda/mapclassify.html
    - There is a jenkspy module on pypi which is implemented in C but distributes windows wheels with each release. https://pypi.python.org/pypi/jenkspy

**Comment by ryanbaumann** [comment]
@perrygeo I think relying on a third party classification lib makes sense here - jenks is just the beginning of classifications users may want to use to calculate a domain of breaks.  

PySAL seems like a great option.

**Comment by ryanbaumann** [comment]
Let's keep data transformation outside of the scope of this library, and instead build examples using PySAL for how to prepare data to use with `mapboxgl`.

I updated the current example notebook to use pySAL to calculate natural breaks.  Here's the [code](https://github.com/mapbox/mapboxgl-jupyter/blob/master/examples/test-mapboxgl-jupyter.ipynb), and the live example at www.mapbox.com/labs/jupyter
