### ISSUE TITLE
is supercluster algorithme used for ClusteredCircleViz

### ISSUE THREAD

**Issue by HADDADENICAR** [mapbox/mapboxgl-jupyter#111]
i found [in this issue](https://github.com/mapbox/supercluster/issues/34) that supercluster is already integrated in **mapbox-gl-js** .
so i  ask if the ClusteredCircleViz is base on it as well ?
if not what is the algorithme on which it is based ?

**Comment by ryanbaumann** [comment]
Yes, the implementation in `mapboxgl-jupyter` is based on the supercluster library bundled with mapboxgl-js.
