### ISSUE TITLE
Rendering issues with multiple extruded layers

### ISSUE THREAD

**Issue by lucasvw** [mapbox/mapboxgl-jupyter#127]
Hi there, I am currently implementing #34 (multi-layer support)

Just running into some weired rendering issues:

![schermafbeelding 2018-10-01 om 14 30 40](https://user-images.githubusercontent.com/4293177/46288879-96705080-c587-11e8-8866-b45e94a727d6.png)

![46289835-755d2f00-c58a-11e8-9006-7bba617cd75a](https://user-images.githubusercontent.com/4293177/46331267-5193fa80-c617-11e8-8ed6-552eba0b6765.png)

This is a visualization in which I add two ChoroplethLayer objects to my MapVisualization object. Both have the same latlon path, they are extruded to different heights, have different colors and width. There seems to be some issue with the rendering order or something.. its probably something to be solved within mapboxgl JS but still wanted to post it here first..

Best,
Lucas

**Comment by lucasvw** [comment]
Here is another shot, on which it might be clearer:

![schermafbeelding 2018-10-01 om 14 57 40](https://user-images.githubusercontent.com/4293177/46289835-755d2f00-c58a-11e8-9006-7bba617cd75a.png)

**Comment by lucasvw** [comment]
Fixed it by refactoring the template to only add the extrusion layer to the map (if extrusion is configured through the options), this fixes it but still its kind of a weird bug. Was also thinking that it might have something to do with this {{belowLayer}} perhaps.. not fully sure though.

**Comment by ryanbaumann** [comment]
This is such a great visualization @lucasvw!  

For this specific bug, were you adding two layers to the map - one line layer and one fill-extrusion layer?

**Comment by ryanbaumann** [comment]
@lucasvw thanks for linking to your code.  In the sample code, the line-on-the-ground layer was plotted `above` the fill extrusion layer in the layer stack.  Thus is makes some sense why the viz shows the symptoms in your sample image.

That brings to mind one thing we'll need to document for multiple layers - the order in which a user adds layers, matters!  Or alternatively, the user can re-order layers in the map.

I'm going to close this issue; but if you run into similar z-fighting while working on multiple layers, let's solve them!
