### ISSUE TITLE
Click on point in CircleViz map

### ISSUE THREAD

**Issue by ecatkins** [mapbox/mapboxgl-jupyter#138]
I have a CircleViz map, in which one of the properties is a hyperlink. Is there a setting that allows me to click through to this hyperlink? Currently, trying to select the label box with the properties,  seems to unselect/unhover the data point in question.

**Comment by akacarlyann** [comment]
@ecatkins the pop-up for each feature in your data is rendered with HTML so there is definitely a way to embed links there. The easiest thing may be to preprocess your data to wrap your urls in HTML link elements but I'll see if I can think of anything else. There is a setting to disable mapclicks that we might need to play with to deal with the behavior I think you're describing. I think I have something similar I can dust off :)

**Comment by ecatkins** [comment]
@akacarlyann Yes, I had already wrapped the url with <a> tags, which works quite well when I render it in other places. If you have a solution to alter the click behavior, that would be amazing!

**Comment by akacarlyann** [comment]
@ecatkins Check out the solution I posted at #139.  You'll want to configure your `CircleViz` instance with `popup_open_action='click'`.  It's a little wordy, but a good option for those who want to click in the popup windows. Hope this helps!

**Comment by ecatkins** [comment]
@akacarlyann Thank you, that seems to work!
