### ISSUE TITLE
Adding a scale in mapboxgl-jupyter

### ISSUE THREAD

**Issue by AnneEstoppey** [mapbox/mapboxgl-jupyter#143]
Hello again

I noticed that there is no possibility to add a scale on the map (Jupyter Notebook, Python 3).

It seems that this possibility exists in the JS version (it was pointed to me by your helpdesk).
See screenshot below.

Would it be possible to also have this feature added in the maboxgl-jupyter?

Cheers :-)
![mapbox_js_scale](https://user-images.githubusercontent.com/35219455/49092841-29192d00-f263-11e8-82e0-7f83820cd9f9.jpg)

**Comment by akacarlyann** [comment]
@AnneEstoppey Definitely, though currently the bottom-left corner is reserved for the Mapbox logo, so we'll have to work out a good way to fit all the info without too much clutter. At this point we have zoom controls, the logo and an attribution enabled by default, with optional legends and map screenshot buttons. I'll look into more of the built-in Mapbox controls too :) Også -- er det sant at du skriver fra Norge?

**Comment by AnneEstoppey** [comment]
Yes, I understand the logo issue, but have a look at google maps how they solved the 'corner map clutter'?
I think a simple line (again ala google maps) would be sufficient. Something very 'lean'.

I think the scale 'object' in the JS version is too clunky, IMO. But this is my opinion (I worked a lot with cartography, thematical mapping, GIS though, but some years ago).

Also why not leave the choice for the user to:
- display a scale or not
- in which corner of the map one wishes to see the scale

Ja jeg bor i Norge, på kartet jeg har limt inn kan du gjette litt kdor. Har flyttet til Norge mange år siden! Og du, er du nordman som har migrert ut? Korifra?

Snakkes :-)
Anne

![google_maps_with_scale](https://user-images.githubusercontent.com/35219455/49140275-2adf0100-f2f4-11e8-9b8f-8fdfe1e3e587.jpg)
