### ISSUE TITLE
Add support to show polygons

### ISSUE THREAD

**Issue by ustroetz** [mapbox/mapboxgl-jupyter#15]
Hi there,

I would like to add support to show polygons. Before I start with an implementation, I would like to discuss with you the best approach.

I was thinking about the following steps:
1. Create a new template `polygon.html`.
2. Create in `viz.py` a new Class `PolygonViz`.
3. Create in `viz.py` a new base Class `Viz`. `PolygonViz`, `GraduatedCircleViz`, and `CircleViz` inherit from this Class. Below is the rough outline of the `Viz` Class.
4. Create one polygon example jupyter notebook that proves the implementation.

I am happy for any feedback about the above. Since I am new to the project, I am also open for a complete different approach to show polygons.

Looking forward to work on this :blush:

-------------
```
class Viz(object):
    """Base class for all visualisations"""

    def __init__(self,
                 access_token=None,
                 center=(0, 0),
                 div_id='map',
                 height='500px',
                 style_url="mapbox://styles/mapbox/light-v9?optimize=true",
                 width='100%',
                 zoom=0):

        if access_token is None:
            access_token = os.environ.get('MAPBOX_ACCESS_TOKEN', '')
        if not access_token.startswith('pk'):
            raise TokenError('Mapbox access token must be public (pk)')
        self.access_token = access_token

        self.div_id = div_id
        self.width = width
        self.height = height
        self.data = data
        self.style_url = style_url
        self.center = center
        self.zoom = zoom

    def as_iframe(self, html_data):
        """Build the HTML representation for the mapviz."""
        ...
       
    def show(self, **kwargs):
        """Load the HTML iframe and display the  the iframe in the current jupyter notebook view"""
        ...
```

**Comment by ryanbaumann** [comment]
@ustroetz sorry for the delay here - yes, we'd love to see a PR including line and polygon visualization support!  I'd recommend using the nomenclature for your line and polygon visualizations as 

a) `line`
b) `fill` (or possibly `choropleth`)

You are exactly right in your approach.  For an example of what adding a new layer type looks like in total, check out the Heatmap PR - https://github.com/mapbox/mapboxgl-jupyter/pull/16

**Comment by ryanbaumann** [comment]
@ustroetz are you interested in submitting a PR for this feature?

**Comment by ustroetz** [comment]
Yes, I actually have a branch sitting here that I want to finish up :)

I'll try to open a PR by the end of the week 🤞

**Comment by ryanbaumann** [comment]
There's an open PR starting this work at https://github.com/mapbox/mapboxgl-jupyter/pull/40

**Comment by ustroetz** [comment]
Glad to see that someone picked up the work! Sorry that I was a bit slow on this.
Awesome to see that there is now so much traction on the project 👏

**Comment by ryanbaumann** [comment]
@akacarlyann  did you get a chance to look at adding in the next step for this issue in your PR https://github.com/mapbox/mapboxgl-jupyter/pull/40?  Looking at what to include in the next release.

**Comment by narlesky** [comment]
@ryanbaumann I have. Not quite done yet but I should have some time opening up in my schedule to work on this later in the week.
