### ISSUE TITLE
Feature request: adjusting opacity

### ISSUE THREAD

**Issue by don-lab-dc** [mapbox/mapboxgl-jupyter#20]
I would be lovely to be able to adjust the opacity of the heatmap, graduated circle, and circle layers, so that the underlying streets are visible.

**Comment by ryanbaumann** [comment]
Agree - I'll put this on the roadmap for the next release @don-lab-dc.  Additionally, it would be great to expose the `layer order` of the visual, which allows the developer to put the data visualization layer anywhere in the map layer stack.  

Currently, we've hard-coded this to be the `waterway-label` layer to work with Mapbox GL styles.

**Comment by ryanbaumann** [comment]
Closed in https://github.com/mapbox/mapboxgl-jupyter/pull/26
