### ISSUE TITLE
raster data layers

### ISSUE THREAD

**Issue by artttt** [mapbox/mapboxgl-jupyter#21]
I see in the roadmap that you want to be able to add raster data layers from numpy arrays.
I wanted that as well so set up a very basic tile server that runs within a jupyter notebook and will project, tile and render a numpy array quickly on the fly.
Its still rough around the edges but works very nicely for me using folium and ipyleaflet to view tiles.
https://github.com/artttt/livemaptiles

**Comment by ryanbaumann** [comment]
@artttt thanks for posting!  We may use this - will leave this issue open as a reference as we build raster support in the future.

**Comment by ryanbaumann** [comment]
This would be a particularly useful feature for interpreting the results of satellite and flyover imagery machine learning analysis.  I.E. you could show the raster data layers and extracted vector features over the top of the raster layers.

**Comment by artttt** [comment]
@ryanbaumann I would help but im about to go on 2 months holiday. (woo hoo)
livemaptiles is already functional for the type of use you suggest. I use it like this almost daily.
Im sure there are many improvements that could be made though, and there might be some benefits of tighter integration into mapboxgl-jupyter although I find it handy how it works with anything that can consume tiles.

**Comment by ryanbaumann** [comment]
Flagging that this is in active development by @vincentsarago in three PRs:

1. Raster Tile layer - https://github.com/mapbox/mapboxgl-jupyter/pull/63
2. Image layer - https://github.com/mapbox/mapboxgl-jupyter/pull/61
3. Local image slippy tile server (extension) - https://github.com/mapbox/mapboxgl-jupyter/pull/64

**Comment by ryanbaumann** [comment]
This shipped, save the local image slippy tile server which is currently WIP.  Closing!
