### ISSUE TITLE
Support for category data in Circle and Graduated Circle Visualization Classes

### ISSUE THREAD

**Issue by akacarlyann** [mapbox/mapboxgl-jupyter#22]
Noticed you have this on your roadmap - I made some small changes to __viz.py__, __circle.html__ and __graduated_circle.html__ allowing user to use Mapbox's "categorical" type to assign circle color or radius.  My implementation includes properties for default color and radius mentioned in #13 .  I have a branch ready to submit as a PR at your convenience.

__viz.py__  
```python
12  class CircleViz(object):
13    """Create a circle map"""
14
15    def __init__(self,
16                 data,
17                 access_token=None,
18                 center=(0, 0),
19                 color_property=None,
20                 color_stops=None,
21                 label_property=None,
22                 color_function_type='interval',
23                 default_color='grey',
24                 div_id='map',
25                 height='500px',
26                 style_url="mapbox://styles/mapbox/light-v9?optimize=true",
27                 width='100%',
28                 zoom=0):
```
etc.

and 

__circle.html__
```
41    map.addLayer({
42        "id": "circle",
43        "source": "data",
44        "type": "circle",
45        "paint": {
46            "circle-color": {
47                // Data property to style color by from python variable
48                "property": "{{ colorProperty }}",
49                // Color stops array to use based on data values from python variable
50                "stops": {{ colorStops }},
51                // Type of function to use for assigning colors provided via colorStops
52                "type": "{{ colorType }}",
53                // Default color for if colorProperty does not match any of color stops
54                "default": "{{ defaultColor }}",
55            },
56            "circle-radius" : {
57                "stops": [[0,1], [18,10]]
58            },
59            "circle-stroke-color": "white",
60            "circle-stroke-width": {
61                "stops": [[0,0.01], [18,1]]
62            }
63        }
64    }, "label");
```

**Comment by ryanbaumann** [comment]
@akacarlyann I like this approach and it's a great starting point.  Please submit a PR.

The only thing you'll need to add is a `generateStepExpression` and `generateMatchExpression` function in `main.html`.  We're mapping all the legacy `stops` functions before GL JS v0.41 to expressions to prepare for a complete swap to full expression support in a future release.  

Here's the existing `generateInterpolateExpression` function for reference - https://github.com/mapbox/mapboxgl-jupyter/blob/master/mapboxgl/templates/main.html#L85

**Comment by akacarlyann** [comment]
@ryanbaumann Thanks, I'll follow up in the new year!

**Comment by ryanbaumann** [comment]
@akacarlyann did you have a branch ready to PR here?  Would love to review and merge in for categorical data.

**Comment by akacarlyann** [comment]
@ryanbaumann Still integrating the updates regarding the stops/expressions conversion but should have something for you soon!
