### ISSUE TITLE
Streaming data architecture

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-jupyter#24]
Investigate creating a streaming data architecture from a Pandas dataframe to a map using the approach in the `Smalltalk` python library https://github.com/murphy214/smalltalk.

**Comment by murphy214** [comment]
There are some interesting things you could do with it i.e. things like [jupyter widgets]( https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html) can help you build a gui for a dataset much easier than in js. Of course your paying for it in loading the dataset into memory every time. 

You could also have something that just renders vector tiles from a data set (dataframe) passively but every time its updated the changes will effect the rendering, a configuration like this would give you more control over different zoom levels and rendering density. Just some thoughts!

Also I'll probably have a read_geojson method for nlgeojson to read directly from a geojson data source to a nlgeojson dataframe easily and I think it should be pretty quick as well!  Currently writing that now!

**Comment by ryanbaumann** [comment]
@murphy214 great notes.  

> Also I'll probably have a read_geojson method for nlgeojson to read directly from a geojson data source to a nlgeojson dataframe easily and I think it should be pretty quick as well! Currently writing that now!

Can you share this when it's ready?  Would love to incorporate this.

**Comment by murphy214** [comment]
Here's the new repo, I gave an example in the read me: https://github.com/murphy214/nlgeojson

There is a chance the install could fail I tested on a vm but I'm actually using compiled golang executables to read the geojson in parallel , and I'm sure there are corner cases that aren't supported however its like 30x faster reading in and you get nlgeojson dfs in the process. 

I'm essentially reading chunks and stitching geojson feature pieces back together [see here](https://github.com/murphy214/geobuf/blob/master/convert_geojson.go#L44) so I'm sure there that if you have a field with '{' or '}' in it its gonna fail, but like I said kind of just hack right now.

**Comment by ryanbaumann** [comment]
@murphy214 just tested nlgeojson - it works great!  A simple architecture, for now, is just to use `nlgeojson` to export a data frame to a local geojson file very fast, and then load the local geojson file in the mapboxgl viz.

Here's an example with 380k earthquake points as a heatmap from the USGS API:

![](https://cl.ly/3W0R280I012V/download/Image%202017-12-27%20at%204.48.28%20PM.png)

**Comment by murphy214** [comment]
Great! Glad it ended up working! It should be quite a bit faster than putting it a normal json serializer/deserializer and it also shouldn't be so ram intensive as well! I really need to build out the read functionality a little more robustly to account for corner cases of "{}" in strings like a real json parser, because I think it could pretty useful to some people. 

Any ideas for incorporations with polygons and/or linestrings? You could always do some UI side filter stuff with Jupyter widgets and it should be entirely possible, however, it probably would be better to handle stuff like that natively in JS.

**Comment by ryanbaumann** [comment]
Agree it could be a very useful utility library @murphy214.  A few things I'm thinking to add:

1. Ability to pass a list of dataframe column names to include in an exported geojson.
2. Remove latitude and longitude from geojson properties since they're already included in the geometry.

Re: Lines and Polygons - That's next on the agenda for this library to offer an easy Pythonic interface for analysts to create choropleths maps. As for sliders and filters - that should be easier to add as render-time filters and style changes with HTML objects.  Mapboxgl is really good at changing data style each frame.  Along with the new Mapboxgl expression syntax, we should be able to handle all the data updates in the viz alone after loading the data once and creating vector tiles.

**Comment by murphy214** [comment]
@ryanbaumann This could be done with minimal refactoring I'll take a look at implementing it tomorrow as I'm currently off for the holidays, it shouldn't take to long! I'll keep you posted!

**Comment by ryanbaumann** [comment]
Modified df_to_geojson() utility function to output a line-delimited geojson file.  https://github.com/mapbox/mapboxgl-jupyter/commit/4cb4ef3c1f32628525172ffeb555f3b46daaa602  

Serving the file locally using the Jupyter Notebook web server works great.  It can be optimized from here, but this is a solid starting point.
