### ISSUE TITLE
Save Map to HTML

### ISSUE THREAD

**Issue by sherl0cks** [mapbox/mapboxgl-jupyter#28]
This is a feature request to save the map to file such that it could be subsequently served to a web browser, a la folium's `save` (see cell 3 in [this example](https://github.com/python-visualization/folium/blob/master/examples/Quickstart.ipynb))

**Comment by sherl0cks** [comment]
appears that you can do something along these lines and works well enough. let me know if there is a more interesting solution. else, we can close this.

```
html = open("100000_markers.html", "w")
html.write( viz.create_html() )
html.close()
```

**Comment by ryanbaumann** [comment]
@sherl0cks this is a very common need - I vote we add an export function for a each viz object.  Html file would be one option, image another option, odd a 3rd option, possibly other options to come.

**Comment by sherl0cks** [comment]
that works for me. we need to make sure the feature it is added to an example when it is built.

**Comment by ryanbaumann** [comment]
@sherl0cks great, added an initial example using your code - see it in this repo at /examples or at www.mapbox.com/labs/jupyter

Let's leave this ticket open as a placeholder for a broader `export viz` functionality.

**Comment by sherl0cks** [comment]
@ryanbaumann nice. thanks for quick turn around

**Comment by ryanbaumann** [comment]
Here is the export to HTML approach captured in the example notebook: 

```
with open('viz.html', 'w') as f:
    f.write(viz.create_html())
```

```
# Python2
python -m SimpleHTTPServer 8080   
```

```
# Python 3
python3 -m http.server 8080   
```

* Now navigate your browser to http://localhost:8080/viz.html to see the viz

**Comment by anderl80** [comment]
Can I share a map with clusters to someone else without starting a web server?

**Comment by ryanbaumann** [comment]
@anderl80 yes, if you include your map `data` parameter as a geojson-format python dictionary, then the data for your map will be packaged up inside your exported map HTML file and can be opened just by opening the HTML file in a browser.
