### ISSUE TITLE
Public documentation

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-jupyter#29]
As the API for mapboxgl-jupyter solidifies:

To hit a 1.0 release, we need great documentation.  Let's use this ticket to track docs to-dos:

- [x] Create documentation generation framework
- [ ] Doc content - viz types
- [ ] Doc content - utilities
- [ ] Doc content - web hosting

cc/ @perrygeo

**Comment by sherl0cks** [comment]
does utilities include the contents of the [color_ramps](https://github.com/mapbox/mapboxgl-jupyter/blob/master/mapboxgl/colors.py#L3) dictionary? for those not inclined to read source code, this a bit cryptic currently, especially until #13 is resolved.

what do you have in mind RE: documentation framework? I'm keen to collaborate here and have a small team that could help test.

**Comment by ryanbaumann** [comment]
@sherl0cks

Agree on #13, we're planning to a) clearly document color options, and b) add default values for color ramps so a user can just pass `mapboxgl.viz.CircleViz(data=data, access_token=token)` and get a valid viz result.

Thanks for the doc collaboration offer - yes, we'd love to collaborate here!  @perrygeo and I will set up the doc generation set up in a new PR, and then we can collab on creating the content.  If you have any examples you'd like to share in the meantime, please open a PR.

**Comment by cmtoomey** [comment]
Additional Documentation specifics

- [ ] Differences between `color_stops` across APIs. What are the individual APIs expecting, and how do these tie back to Mapbox Style-spec requirements. Specifically for Heatmaps, there could be additional explanation as to how these values are interpreted and rendered. 

Example:

Heatmap requires a color stop that looks like this: `heatmap_color_stops = mapboxgl.colors.create_color_stops([0.01,0.25,0.5,0.75,1], colors='RdPu')`

Clustered looks like this: `color_stops = mapboxgl.colors.create_color_stops([1,10,50,100], colors='RdPu')`

Points utilize a standard set of stops from `create_color_stops` but it appears that Heatmap and Clustered are looking for values across a specific range. If this is the case, it should be documented.

**Comment by ryanbaumann** [comment]
Let's push on documentation this month.  The goal would be to enable a 1.0 release by the end of February.  @perrygeo any recommendations on a Python documentation system to use to publish website docs?

**Comment by perrygeo** [comment]
Sphinx is the gold standard: http://www.sphinx-doc.org/en/stable/

Configuration is a little tricky and it uses RestructuredText instead of markdown - but it's flexible with very nice HTML output.

**Comment by ryanbaumann** [comment]
Thanks @perrygeo.  Let's break out several doc tasks:

1. Setup Sphinx framework
2. Generate viz docs for parent viz objects (style, access_token, etc)
3. Generate viz docs copy for each specific viz type (circle, graduated circle, heatmap, clustered circle, and choropleth)

**Comment by ryanbaumann** [comment]
Sphix docs are setup.  Need to format the docs and create the copy now.  New merges will automatically publish to readthedocs.org at

https://mapboxgl-jupyter.readthedocs.io/en/latest/mapboxgl.html

**Comment by ryanbaumann** [comment]
@markmisener is moving on a markdown version of the docs here to host on Github - https://github.com/mapbox/mapboxgl-jupyter/pull/46

**Comment by narlesky** [comment]
Does this mean veering away from readthedocs site?  Or will we port over the markdown files once all of the copy is written?

**Comment by ryanbaumann** [comment]
@narlesky yes.  Apologies if we're crossing streams here.  

We're planning to use markdown documentation for the initial launch, and delay the readthedocs / Sphinx docs implementation until a later release.

**Comment by narlesky** [comment]
:+1:

**Comment by ryanbaumann** [comment]
The markdown version of the docs are live!  Let's continue to use the markdown docs moving forward.
