### ISSUE TITLE
Clicking on point should not re-zoom the map

### ISSUE THREAD

**Issue by cmtoomey** [mapbox/mapboxgl-jupyter#31]
Currently, when a user clicks on a point, the map will snap to that point at the default zoom (or what is specified as a arg). 

The map should not zoom out based on interaction with a point

![zoomjupyter](https://user-images.githubusercontent.com/12201602/34502392-199cf6ca-efc8-11e7-958a-c8ffd76bdf91.gif)

**Comment by akacarlyann** [comment]
See line 90 in circle.html (91 in graduated_circle.html and 105 in clustered_circle.html for similar):
```
    // Fly to on click
    map.on('click', 'circle', function(e) {
        map.flyTo({
            center: e.features[0].geometry.coordinates,
            zoom: 10
        });
    });
```

Can zoom just be omitted in these places to address this issue?

**Comment by ryanbaumann** [comment]
@akacarlyann yes, agree that changing the zoom behavior change is the simple fix here.  

One default option that I think is common is to `zoom` the map in +1 level when clicking on a point.  That would mean:

```
    // Fly to on click
    map.on('click', 'circle', function(e) {
        map.flyTo({
            center: e.features[0].geometry.coordinates, //center viewport on clicked feature
            zoom: map.getZoom() + 1  //add 1 to current zoom level
        });
    });
```
