### ISSUE TITLE
Accept custom color palettes in create_color_stops()

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-jupyter#51]
# Problem

Currently, the `create_color_stops` function accepts a string that defines a color palette from ColorBrewer.  This function should also allow the user to pass a custom color palette as a list of color strings.  The documentation claims this is possible today, but it is not yet implemented.

# Solution

Make a PR to add support for passing a custom list of colors to `create_color_stops` -> https://github.com/mapbox/mapboxgl-jupyter/blob/master/mapboxgl/utils.py#L109

cc @pveugen

**Comment by ppessi** [comment]
Should it contain a check for if the list is valid?

**Comment by ppessi** [comment]
I don't know how to read, I thought that the reference by ryanbaumann was a reference from another issue and not a commit :D Oh well

**Comment by ryanbaumann** [comment]
I like your implementation, thanks for the PR @ppessi!  I'll use your suggested color checking method in the existing PR, it's cleaner and doesn't require another library dependancy -> https://github.com/mapbox/mapboxgl-jupyter/pull/54/commits/993b71955d63b8571d33ae67d0c310b65b8cf3c9
