### ISSUE TITLE
color_property, radius_property not used by ClusteredCircleViz

### ISSUE THREAD

**Issue by scwilkinson** [mapbox/mapboxgl-jupyter#53]
I'm attempting to use a color_property or radius_property with a ClusteredCircleViz, which the [table of params](https://github.com/mapbox/mapboxgl-jupyter/blob/master/docs-markdown/viz.md#class-clusteredcircleviz) includes. However, from looking at the source and the errors I'm getting, these options don't seem to be present!

Is this an issue with the documentation?

**Comment by akacarlyann** [comment]
@scwilkinson can you post an example of what you are trying to do? In the source, __ClusteredCircleViz__ takes both _color_property_ and _radius_property_ as keyword arguments. Looks like this _is_ missing from the docs for initializing a __ClusteredCircleViz__ at the moment.

**Comment by scwilkinson** [comment]
I'm trying to do something like:

```
import pandas as pd
import os
from mapboxgl.utils import *
from mapboxgl.viz import *

# Load data from sample csv
data_url = 'https://raw.githubusercontent.com/mapbox/mapboxgl-jupyter/master/examples/points.csv'
df = pd.read_csv(data_url)

# Create a geojson file export from a Pandas dataframe
data = df_to_geojson(df,
              properties=['Avg Medicare Payments', 'Avg Covered Charges', 'date'],
                     lat='lat', lon='lon', precision=3)

#Create a clustered circle map
color_stops = create_color_stops([1,10,50,100], colors='BrBG')

viz = ClusteredCircleViz(data,
                          access_token=token,
                          color_stops = color_stops,
                          radius_stops = [[1,5], [10, 10], [50, 15], [100, 20]],
                          cluster_maxzoom = 10,
                          cluster_radius = 30,
                          opacity = 0.9,
                          center = (-95, 40),
                          zoom = 3,
                          color_property = 'Avg Medicare Payments',
                          radius_property = 'Avg Covered Charges'
                        )

viz.show()
```

However I get:

```TypeError: __init__() got an unexpected keyword argument 'color_property'```

**Comment by scwilkinson** [comment]
@akacarlyann I'd like to be able to combine a GraduatedCircleViz with a ClusteredCircleViz in some way. In my case I'm weighting points with some factor and I'd like the size of the cluster circles reflect the sum of these weights.

For example, let's say we've got a list of houses with occupancy. With a ClusteredCircleViz we're forced to have cluster circles that reflect the sum of houses in a region. However, it might be nice to use the sum of occupancies instead. While we could do this with a GraduatedCircleViz, it would be crazy dense, so a ClusteredCircleViz would be awesome!
