### ISSUE TITLE
CircleViz doesn't plot data if color_stops is None

### ISSUE THREAD

**Issue by EtienneDesticourt** [mapbox/mapboxgl-jupyter#60]
Hi,  

I was trying to plot a CircleViz and my points wouldn't appear. Once I supplied the color_stops argument they showed up.
If color_stops are required to plot data they should raise an error when missing, or be set to a meaningful default.
Related to #13 I think.

Cheers

**Comment by ryanbaumann** [comment]
Closed in https://github.com/mapbox/mapboxgl-jupyter/pull/78
