### ISSUE TITLE
Enable `data` for any viz to come from a vector tile source

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-jupyter#71]
# Problem

Currently, each viz class `data` object only supports geojson format data from a URL or local variable geoJSON format object.  We should enable users to pass a data as a vector tile source.

# Implementation

I propose we maintain that the `data` object should be a URL or local geoJSON format object.  We can add another optional parameter to each parent viz class named `vector_source_layername`.  This will parameter specifies the name of the vector tile layer to create the visual from a layer in a vector tile.  

If the user passes the optional `vector_source_layername` parameter, the visualization will create a layer from a vector tile source instead of a geojson source.

**Comment by ryanbaumann** [comment]
Adding this to the 0.7.0 release - it's super powerful to connect any vector tile source to any visualization type with essentially infinite data volume.  The only exception we'll need to make here is for `cluster` maps, which are not compatible with Mapbox Vector Tile sources.

# To Do

- [ ] Accept a vector tile URL as in the map `data` parameter
- [ ] Add a new parameter to the map, `dataLayerName`.  Accept a string value here that maps to the vector tile source's layer name.  
- [ ] If the datatype argument is set to `vectortile`, change the map.addSource() call in each template to point to the `vector` type and `url` argument.  Also change the map.addLayer() call in each template to use the `source-layername` of the vector tile.
- [ ] Create tests
- [ ] Create example notebook using vector tile sources for each visualization type (all except Cluster)

**Comment by akacarlyann** [comment]
@ryanbaumann I'm willing to work on this one (it also helps with the multi-layer maps) but often struggle to find good test data. Can you possibly create and share a vector layer of the healthcare example data so I can work the data join with example data we already have in this project?

**Comment by ryanbaumann** [comment]
@akacarlyann that's amazing - thank you for offering to help!

I have.....a lot of tilesets you can test with.  Here's a public tileset of the healthcare data that you can use with any Mapbox access token - `rsbaumann.2pgmr66a`

**Comment by akacarlyann** [comment]
@ryanbaumann Thanks!  What's the name of the layer for that vector dataset?

**Comment by ryanbaumann** [comment]
@akacarlyann updated the comment above with the source-layer name of the tileset.

**Comment by akacarlyann** [comment]
@ryanbaumann  I've got CircleViz and GraduatedCircleViz working with vector tiles, so thanks for that!  Per https://github.com/mapbox/mapbox-gl-js/issues/5856, looks like cluster maps don't support using vector source data at this time.  Thoughts on if we should punt this or ...?

**Comment by ryanbaumann** [comment]
This is awesome!  Unlocks the ability to run a bigger data analysis, cut vector tiles from the analysis, and visualize them right in Jupyter.  Yes, we'll need to integrate a tool to cut vector tiles, ideally using `tippecanoe` for maximum performance.

>looks like cluster maps don't support using vector source data at this time

Correct - you can cluster data to put into a vector tile source using Tippecanoe, but can not create a cluster from a vector tile source on the fly without some custom code.  Agreed, skip support for vector tile sources on a cluster.
