### ISSUE TITLE
Add function for showing map in Databricks notebook

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-jupyter#75]
Databricks notebooks use the `displayHTML` function instead of Jupyter's `display` function to show HTML in a results pane. 

We should adopt the `show` function to work with dataBricks notebooks, by falling back to the `displayHTML` function if needed.  A secondary option would be to add a `viz.showDatabricks()` function.

**Comment by ryanbaumann** [comment]
I'm thinking we could handle this easily by just checking if the `displayHTML` function exists in the project session, and using that function if it exists.

**Comment by glebmezh** [comment]
@ryanbaumann I tried using 


```
html = viz.create_html()
displayHTML(html)
```
in Databricks, but the map does not render for some reason. No errors either. I used the example from the man page.

**Comment by akacarlyann** [comment]
@glebmezh Did you ever come up with a solution to this?  I'm wondering what happens if you try
```
from IPython.core.display import HTML, display

html = viz.create_html()
displayHTML(HTML(html))

```
I have no experience with Databricks, but I'd love to help get this checked off.

**Comment by globetro** [comment]
You can display in a DataBricks notebook via:

```
displayHTML(viz.as_iframe(viz.create_html()))
```

**Comment by ryanbaumann** [comment]
Thanks @globetro .  Let's use your suggestion as the accepted solution.
