### ISSUE TITLE
Add 3D `height` option to ChoroplethViz

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-jupyter#83]
Add support to `extrude` a Choropleth polygon layer.  Expose the option as `height*` properties to the Choropleth Viz.  

* `height_stops`
* `height_property`
* `height_default`

Example Viz: 3D Population Density - www.mapbox.com/bites/00273

![](https://cl.ly/0s3n0j463k24/download/Image%202018-03-25%20at%207.09.37%20PM.png)

**Comment by akacarlyann** [comment]
@ryanbaumann I've started on this.  I basically lifted the scheme for calculating the weight stops for a heatmap or radius stops, but had to greatly exaggerate the height gradient for visibility on the map.  I'll submit a PR for your review :)

<img width="866" alt="extruded choropleth" src="https://user-images.githubusercontent.com/13527707/38168935-7449cbf6-3510-11e8-8a86-53982de98a3b.png">
