### ISSUE TITLE
Unfilled choropleth cells

### ISSUE THREAD

**Issue by bnaul** [mapbox/mapboxgl-jupyter#93]
I've noticed that often some cells will not receive a color depending on the corresponding value. I uploaded an example GeoJSON that reproduces this behavior on the latest master:
```
viz = ChoroplethViz('https://gist.githubusercontent.com/bnaul/9cabfecc998ea8ffce5aa0b44afc1dda/raw/b7f88c5c7d13306851d220ded36445395c45bf17/example.json',
                    access_token=TOKEN,
                    color_property='mean_household_income',
                    color_stops=create_color_stops([20_000, 60_000, 100_000, 200_000], colors='Blues'),
                    color_function_type='interpolate',
                    line_color='rgb(38,0,128)',
                    center=(-79.95, 43.75),
                    height='800px',
                    zoom=11,
                    )
viz.show()
```
![screen shot 2018-04-20 at 3 18 25 pm](https://user-images.githubusercontent.com/903655/39076098-39f7e2d2-44ae-11e8-9fd8-2dfe13555077.png)
I thought maybe there was something wrong with the polygons themselves, but changing the color stops fixes the issue (here I just divided all the color stops by 100):
![screen shot 2018-04-20 at 3 17 26 pm](https://user-images.githubusercontent.com/903655/39076101-3daadb8c-44ae-11e8-9d2b-252bd95f1347.png)

Anecdotally this seems more likely to affect values near the middle of the scale, but that could be my imagination...

**Comment by akacarlyann** [comment]
@bnaul Thanks for the heads up!  The line change I mention below may correct the problem for you.

@ryanbaumann I think this may be related to difference in behavior for an exponential interpolation versus the linear interpolation that was originally in place.  I was able to display the colors properly by changing line 96 in __main.html__ from ```expression = ['interpolate', ['exponential', 1.2], ['get', propertyValue]]``` to ```expression = ['interpolate', ['linear'], ['get', propertyValue]]```.

<img width="669" alt="screen shot 2018-04-20 at 4 35 18 pm" src="https://user-images.githubusercontent.com/13527707/39077722-d62a0e78-44b8-11e8-91df-59c1d0b3aa39.png">

For context:

```
function generateInterpolateExpression(propertyValue, stops) {
    var expression;
    if (propertyValue == 'zoom') {
        expression = ['interpolate', ['exponential', 1.2], ['zoom']]
    }
    else if (propertyValue == 'heatmap-density') {
        expression = ['interpolate', ['exponential', 1.2], ['heatmap-density']]
    }
    else {
        expression = ['interpolate', ['linear'], ['get', propertyValue]]
    }

    for (var i=0; i<stops.length; i++) {
        expression.push(stops[i][0], stops[i][1])
    }
    return expression
}
```

**Comment by ryanbaumann** [comment]
@akacarlyann yes, that should fix this issue.  Expressions for non-zoom driven functions should scale linearly by default.

**Comment by akacarlyann** [comment]
Sweet. That also resolves a slight mismatch in color computation for vector vizes vs geojson choropleth maps.
